# Generated by Django 5.2.1 on 2025-05-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('studentid', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('passwordhash', models.CharField(max_length=255)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('gradelevel', models.CharField(blank=True, max_length=50, null=True)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
