# Generated by Django 5.2.1 on 2025-07-08 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='mentor_profiles/')),
                ('phone_number', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('total_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_students', models.CharField(choices=[('high_school', 'High School'), ('college', 'College'), ('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('professional', 'Professional'), ('other', 'Other')], max_length=20)),
                ('preferred_language', models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish'), ('french', 'French'), ('bangla', 'Bangla'), ('hindi', 'Hindi'), ('arabic', 'Arabic'), ('chinese', 'Chinese'), ('german', 'German'), ('japanese', 'Japanese'), ('portuguese', 'Portuguese'), ('russian', 'Russian'), ('other', 'Other')], max_length=20)),
                ('ok_with_disabilities', models.BooleanField(default=False)),
                ('ok_with_diversity', models.BooleanField(default=False)),
                ('communication_methods', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App Notifications')], default='email', max_length=100)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('other', 'Other')], default='bank_transfer', max_length=30)),
                ('payout_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('on_demand', 'On Demand')], default='monthly', max_length=20)),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='mentors.mentorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('responsibility', models.TextField(blank=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_experiences', to='mentors.mentorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_at', models.CharField(max_length=100)),
                ('teaching_philosophy', models.TextField()),
                ('teaching_method', models.CharField(choices=[('one_on_one', '1:1'), ('group', 'Group')], max_length=20)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertises', to='mentors.mentorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('from_year', models.PositiveIntegerField()),
                ('to_year', models.PositiveIntegerField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='mentors.mentorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='mentors.mentorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='mentors.expertise')),
            ],
        ),
    ]
