# Generated by Django 5.2.1 on 2025-07-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='is_onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='onboarding_step',
            field=models.IntegerField(default=1),
        ),
    ]
