# Generated by Django 5.2.1 on 2025-07-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_students_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table=None,
        ),
    ]
