# Generated by Django 5.2.1 on 2025-07-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_students_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='updatedat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
