# Generated by Django 5.2.1 on 2025-07-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_students_email_remove_students_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
