# Generated by Django 5.2.1 on 2025-07-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_students_first_name_students_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='rofile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
