# Generated by Django 5.2.1 on 2025-07-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_students_rofile_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='rofile_completed',
        ),
    ]
