# Generated by Django 5.2.1 on 2025-07-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_students_rofile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
